#:schema https://json.schemastore.org/pyproject.json

[project]
name = "vc-research-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "networkx>=3.4.2",
    "scipy>=1.15.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ruff>=0.11.0",
]

[tools.ruff]
extend-select = ["I"]
